distInfo=list(
  Uniform=list(parName=c('lowBound','highBound'),
               parLongName=c('lower bound','upper bound'),
               parSymbol=c('a','b'),
               constraints=c('a<b'),
               url='https://en.wikipedia.org/wiki/Continuous_uniform_distribution',
               note=NULL,
               warning=NULL),
  Normal=list(parName=c('mean','sd'),
              parLongName=c('mean','standard deviation'),
              parSymbol=c('mu','sigma'),
              constraints=c('sigma>0'),
              url='https://en.wikipedia.org/wiki/Normal_distribution',
              note=NULL,
              warning=NULL),
  LogNormal=list(parName=c('meanlog','sdlog'),
                 parLongName=c('mean of log-variable','standard deviation of log-variable'),
                 parSymbol=c('mu','sigma'),
                 constraints=c('sigma>0'),
                 url='https://en.wikipedia.org/wiki/Log-normal_distribution',
                 note=NULL,
                 warning=NULL),
  Gumbel=list(parName=c('location','scale'),
              parLongName=c('location','scale'),
              parSymbol=c('mu','sigma'),
              constraints=c('sigma>0'),
              url='https://en.wikipedia.org/wiki/Gumbel_distribution',
              note=NULL,
              warning=NULL),
  Exponential1=list(parName=c('scale'),
                    parLongName=c('scale'),
                    parSymbol=c('sigma'),
                    constraints=c('sigma>0'),
                    url='https://en.wikipedia.org/wiki/Exponential_distribution',
                    note='Assumes a lower threshold equal to zero',
                    warning='The second parameter is the scale and NOT the rate (scale = 1/rate)'),
  Exponential2=list(parName=c('threshold','scale'),
                    parLongName=c('threshold','scale'),
                    parSymbol=c('mu','sigma'),
                    constraints=c('sigma>0'),
                    url='https://en.wikipedia.org/wiki/Exponential_distribution',
                    note='This is just a shift of the standard exponential distribution (the latter corresponding to mu=0)',
                    warning='The second parameter is the scale and NOT the rate (scale = 1/rate)'),
  GEV=list(parName=c('location','scale','shape'),
           parLongName=c('location','scale','shape'),
           parSymbol=c('mu','sigma','xi'),
           constraints=c('sigma>0'),
           url='https://en.wikipedia.org/wiki/Generalized_extreme_value_distribution',
           note='xi=0 leads to the Gumbel distribution',
           warning='xi < 0 corresponds to a heavy right tail, xi > 0 to a right-bounded distribution. This is THE OPPOSITE of the parameterization used in e.g. wikipedia or R package evd'),
  GPD2=list(parName=c('scale','shape'),
            parLongName=c('scale','shape'),
            parSymbol=c('sigma','xi'),
            constraints=c('sigma>0'),
            url='https://en.wikipedia.org/wiki/Generalized_Pareto_distribution',
            note='xi=0 leads to the exponential distribution; assumes a lower threshold equal to zero',
            warning='xi < 0 corresponds to a heavy right tail, xi > 0 to a right-bounded distribution. This is THE OPPOSITE of the parameterization used in e.g. wikipedia or R package evd'),
  GPD3=list(parName=c('threshold','scale','shape'),
            parLongName=c('threshold','scale','shape'),
            parSymbol=c('mu','sigma','xi'),
            constraints=c('sigma>0'),
            url='https://en.wikipedia.org/wiki/Generalized_Pareto_distribution',
            note='xi=0 leads to the exponential distribution; GPD2 is a special case of GPD3 with mu=0',
            warning='xi < 0 corresponds to a heavy right tail, xi > 0 to a right-bounded distribution. This is THE OPPOSITE of the parameterization used in e.g. wikipedia or R package evd'),
  Poisson=list(parName=c('rate'),
               parLongName=c('rate'),
               parSymbol=c('lambda'),
               constraints=c('lambda>0'),
               url='https://en.wikipedia.org/wiki/Poisson_distribution',
               note=NULL,
               warning=NULL),
  PearsonIII=list(parName=c('location','scale','shape'),
                  parLongName=c('location','scale','shape'),
                  parSymbol=c('mu','sigma','xi'),
                  constraints=c('sigma!=0','xi>0'),
                  url='https://www.rdocumentation.org/packages/PearsonDS/versions/1.2/topics/PearsonIII',
                  note=NULL,
                  warning=NULL),
  LogPearsonIII=list(parName=c('locationlog','scalelog','shapelog'),
                     parLongName=c('location of log-variable','scale of log-variable','shape of log-variable'),
                     parSymbol=c('mu','sigma','xi'),
                     constraints=c('sigma!=0','xi>0'),
                     url='https://www.rdocumentation.org/packages/PearsonDS/versions/1.2/topics/PearsonIII',
                     note=NULL,
                     warning=NULL),
  Gumbel_min=list(parName=c('location','scale'),
                  parLongName=c('location','scale'),
                  parSymbol=c('mu','sigma'),
                  constraints=c('sigma>0'),
                  url='https://en.wikipedia.org/wiki/Generalized_extreme_value_distribution#Modification_for_minima_rather_than_maxima',
                  note=c('Gumbel for minima is a distribution family distinct from the standard Gumbel.',
                         'It is derived from the equality: min(x)=-1*max(-x). Consequently:',
                         'f_{Gumbel_min}(x;mu,sigma) = f_{Gumbel}(-x;-mu,sigma)',
                         'F_{Gumbel_min}(x;mu,sigma) = 1 - F_{Gumbel}(-x;-mu,sigma)',
                         'Q_{Gumbel_min}(p;mu,sigma) = -1*Q_{Gumbel}(1-p;-mu,sigma)',
                         'RANDOM_{Gumbel_min}(mu,sigma) = -1*RANDOM_{Gumbel}(-mu,sigma)'),
                  warning=NULL),
  GEV_min=list(parName=c('location','scale','shape'),
               parLongName=c('location','scale','shape'),
               parSymbol=c('mu','sigma','xi'),
               constraints=c('sigma>0'),
               url='https://en.wikipedia.org/wiki/Generalized_extreme_value_distribution#Modification_for_minima_rather_than_maxima',
               note=c('GEV for minima is a distribution family distinct from the standard GEV.',
                      'It is derived from the equality: min(x)=-1*max(-x). Consequently:',
                      'f_{GEV_min}(x;mu,sigma,xi) = f_{GEV}(-x;-mu,sigma,xi)',
                      'F_{GEV_min}(x;mu,sigma,xi) = 1 - F_{GEV}(-x;-mu,sigma,xi)',
                      'Q_{GEV_min}(p;mu,sigma,xi) = -1*Q_{GEV}(1-p;-mu,sigma,xi)',
                      'RANDOM_{GEV_min}(mu,sigma,xi) = -1*RANDOM_{GEV}(-mu,sigma,xi)'),
               warning='see GEV warning for parameterization of the shape parameter xi'),
  GEV_min_pos=list(parName=c('location','scale'),
                   parLongName=c('location','scale'),
                   parSymbol=c('mu','sigma'),
                   constraints=c('sigma>0'),
                   url='https://en.wikipedia.org/wiki/Generalized_extreme_value_distribution#Modification_for_minima_rather_than_maxima',
                   note=c('This is a GEV_min with shape parameter fixed to xi=sigma/mu.',
                          'The resulting distribution has a lower bound equal to zero, which may be realistic for e.g. low flows.'),
                   warning='see GEV warning for parameterization of the shape parameter xi'),
  FlatPrior=list(parName=c(),
                 parLongName=c(),
                 parSymbol=c(),
                 constraints=c(),
                 url='https://en.wikipedia.org/wiki/Prior_probability#Examples',
                 note='improper distribution corresponding to a uniform distribution on (-infinity;+infinity)',
                 warning='should only be used as a prior distribution'),
  Triangle=list(parName=c('Peak','lowBound','highBound'),
               parLongName=c('Peak','lower bound','upper bound'),
               parSymbol=c('c','a','b'),
               constraints=c('a<c<b'),
               url='https://en.wikipedia.org/wiki/Triangular_distribution',
               note=NULL,
               warning=NULL)
)

save(distInfo,file='../data/distInfo.RData')
